name: python-final


services:
  db_postgresql:
    container_name: postgres_app
    build: ./_CI/db/postgresql
    restart: always
    ports:
      - ${DB_POSTGRES_PORT_IN}:${DB_POSTGRES_PORT_OUT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_POSTGRES_NAME_DB}
      - POSTGRES_USER=${DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}

  db_mysql:
    container_name: mysql_app
    build: ./_CI/db/mysql
    restart: always
    ports:
      - ${DB_MYSQL_PORT_IN}:${DB_MYSQL_PORT_OUT}
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_POSTGRES_PASSWORD}
      - MYSQL_DATABASE=${DB_POSTGRES_NAME_DB}
      - MYSQL_USER=${DB_POSTGRES_USER}
      - MYSQL_PASSWORD=${DB_POSTGRES_PASSWORD}

  data_generator:
    container_name: data_generator_app
    build:
      context: ./
      dockerfile: ./_CI/generator/Dockerfile
    depends_on:
      - db_postgresql

volumes:
  postgres_data:
  mysql_data: