name: python-final


services:
  db_postgresql:
    container_name: postgres_app
    build: ./_CI/db
    restart: always
    ports:
      - ${DB_PORT_IN}:${DB_PORT_OUT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME_DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  data_generator:
    container_name: data_generator_app
    build:
      context: ./
      dockerfile: ./_CI/generator/Dockerfile
    depends_on:
      - db_postgresql

volumes:
  postgres_data: